language: php

php:
  - 7.1
  - 7.2
  - 7.3

cache:
  directories:
    - $HOME/.composer/cache

services: mongodb

before_install:
  - if [[ $(phpenv version-name) = "7.1" ]]; then pecl install mongodb; fi
  - echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

before_script:
  - composer install --no-interaction

script:
  - vendor/bin/phpcs
  - vendor/bin/phpunit -c phpunit.xml.dist

after_script:
  - php vendor/bin/coveralls -v

matrix:
  allow_failures:
    - php: 7.3
