language: php

php:
  - 7.2
  - 7.3

cache:
  directories:
    - $HOME/.composer/cache

services: mongodb

before_install:
  - echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

before_script:
  - composer install --no-interaction

script:
  - vendor/bin/phpcs
  - vendor/bin/phpunit -c phpunit.xml.dist

after_success:
  - if [[ $(phpenv version-name) = "7.2" ]]; then php vendor/bin/php-coveralls -v; fi
